stages:
  # ... (your existing stages)

  Training:
    cmd: python src/components/model_training.py
    deps:
      - src/components/model_training.py
      - src/utils.py
      - src/logger.py
      - src/exception.py
      - params.yaml
      - data/processed/X_train.npy
      - data/processed/X_test.npy
      - data/processed/y_train.npy
      - data/processed/y_test.npy
    outs:
      - checkpoints/${configs.model_name}.pkl
      - artifacts/classification_report.txt
      - artifacts/y_pred.csv
      - artifacts/y_test.csv
    metrics:
      - artifacts/metrics.json
    plots:
      # - confusion: # different x and y paths
      #     y: artifacts/y_pred.csv
      #     x: artifacts/y_test.csv
      #     template: confusion

      - artifacts/auc_plot.png
      - artifacts/confusion_matrix.png
      - artifacts/pr_curve.png
