configs:
    raw_data_dir: ./data/raw
    dataset_api: "nitinchoudhary012/algerian-forest-fires-dataset"
    data_file_name: Algerian_forest_fires_dataset.csv
    processed_data_dir: ./data/processed
    artifacts_path: ./artifacts
    checkpoints: ./checkpoints
    test_size: 0.3
    target_column: Classes
    scoring: roc_auc
    cv: 5
    scaling_method: minmax # minmax or standard
    model_name: KNN # Change this to the model you want to use

model_params:
    # RF
    # n_estimators: 5
    # max_depth: 5
    # min_samples_split: 5

    # DT
    # criterion: "gini"
    # splitter: "best"
    # max_depth: 5
    # min_samples_split: 5
    # min_samples_leaf: 5

    # GradientBoost
    # loss: "log_loss"
    # learning_rate: 0.1
    # n_estimators: 10
    # max_depth: 4
    # random_state: 42

    # LR
    # C: 1.0
    # penalty: "l2"
    # solver: "lbfgs"

    # SVC
    # C: 1.0
    # kernel: "linear"
    # gamma: "scale"
    # probability: True

    # KNN
    n_neighbors: 5
    weights: "uniform"
    algorithm: "auto"
    leaf_size: 15

    # AdaBoost
    # n_estimators: 10
    # learning_rate: 0.01
    # random_state: 42

    # LDA
    # solver: "svd"
    # store_covariance: True
    # tol: 0.0001

    # QDA
    # reg_param: 0.0
    # tol: 0.0001
