paths:
    raw_data_path: ./data/raw/Algerian_forest_fires.csv
    train_data_path: ./data/processed/train_data.csv
    eval_data_path: ./data/processed/eval_data.csv
    artifacts_path: './artifacts'
    checkpoints_path: './checkpoints'

hyperparams:
    test_size: 0.2
    target_column: 'Classes'

