configs:
    raw_data_dir: ./data/raw
    dataset_api: "nitinchoudhary012/algerian-forest-fires-dataset"
    data_file_name: Algerian_forest_fires_dataset.csv
    processed_data_dir: ./data/processed
    artifacts_path: ./artifacts
    checkpoints: ./checkpoints
    test_size: 0.2
    target_column: Classes
    scoring: roc_auc
    cv: 5
    scaling_method: minmax # or standard
    model_name: DecisionTreeClassifier # Change this to the model you want to use

model_params:
    # RandomForestClassifier
    # n_estimators: 10
    # max_depth: 5
    # min_samples_split: 5

    # DecisionTreeClassifier
    criterion: "gini"
    splitter: "best"
    max_depth: 5
    min_samples_split: 5
    min_samples_leaf: 5

    # GradientBoostingClassifier
    # loss: "log_loss"
    # learning_rate: 0.1
    # n_estimators: 100
    # max_depth: 4
    # random_state: 42

    # LogisticRegression
    # C: 1.0
    # penalty: "l2"
    # solver: "lbfgs"

    # SVC
    # C: 1.0
    # kernel: 'rbf'
    # gamma: 'scale'
    # probability: True

    # KNeighborsClassifier
    # n_neighbors: 5
    # weights: 'uniform'
    # algorithm: 'auto'
    # leaf_size: 30

    # AdaBoostClassifier
    # n_estimators: 50
    # learning_rate: 1.0
    # random_state: ${SEED}

    # LinearDiscriminantAnalysis
    # solver: 'svd'
    # store_covariance: True
    # tol: 0.0001

    # QuadraticDiscriminantAnalysis
    # reg_param: 0.0
    # tol: 0.0001
