configs:
    raw_data_path: ./data/raw/Algerian_forest_fires.csv
    train_data_path: ./data/processed/train_data.csv
    eval_data_path: ./data/processed/eval_data.csv
    artifacts_path: './artifacts'
    checkpoints_path: './checkpoints'
    test_size: 0.2
    target_column: 'classes'
    scoring: 'auc_roc'
    cv: 5

model_params:
    - name: "RandomForestClassifier"
      params:
        n_estimators: 50
        max_depth: 5
        min_samples_split: 5
    
  # - name: "DecisionTreeClassifier"
  #   params:
  #     n_estimators: 50
  #     max_depth: 5
  #     min_samples_split: 5
  # - name: "GradientBoostingClassifier"
  #   params:
  #     n_estimators: [50, 100, 200]
  #     learning_rate: [0.01, 0.1, 1]
  #     max_depth: [3, 5, 10]
  #     min_samples_split: [2, 5, 10]
  #     min_samples_leaf: [1, 2, 4]
  #     max_features: ['auto', 'sqrt', 'log2']
  # - name: "LogisticRegression"
  #   params:
  #     C: 1.0
  #     penalty: 'l2'
  #     solver: 'lbfgs'
  # - name: "XGBClassifier"
  #   params:
  #     n_estimators: 50
  #     learning_rate: 0.01
  #     max_depth: 5
  #     min_child_weight: 3
  #     gamma: 0.1
  # - name: "CatBoostClassifier"
  #   params:
  #     iterations: 50
  #     learning_rate: 0.1
  #     depth: 5
  #     l2_leaf_reg: 3
  # - name: "AdaBoostClassifier"
  #   params:
  #     n_estimators: 100
  #     learning_rate: 0.1