configs:
    raw_data_dir: ./data/raw
    data_file_name: algerian_forest_fires_dataset.csv
    cleaned_data_dir: ./data/cleaned
    artifacts_path: ./artifacts
    checkpoints_path: ./checkpoints
    test_size: 0.2
    target_column: 'Classes'
    scoring: 'roc_auc'
    cv: 5
    scaling_method: 'minmax' # or "standard"
    model_name: "RandomForestClassifier"

model_params:
    n_estimators: 50
    max_depth: 5
    min_samples_split: 5
