name: CI Prediction Model

on:
  # workflow_dispatch:
  push:
    branches:
  #     - develop
  #   paths:
  #     - src/**
  # pull_request:
  #   branches:
  #     - develop
  #   paths:
  #     - src/**

permissions: write-all
  # contents: read
  # id-token: write
jobs:
  experiment:
    environment: env
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"  
  
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: iterative/setup-cml@v1
    - uses: iterative/setup-dvc@v1

    - name: Configure Git
      run: |
        git config --global user.name "heba"14101998
        git config --global user.email "mohamedheba1998@gmail.com"
        git config --global credential.helper store
        git config --global user.password ${{ secrets.GITHUB_TOKEN }}

    - name: Create Kaggle Authentication Token file
      run: |
        mkdir -p ~/.kaggle
        echo ${{ secrets.KAGGLE_TOKEN_BASE64 }} | base64 --decode > ~/.kaggle/kaggle.json
        sudo chmod 600 ~/.kaggle/kaggle.json
        ls -al ~/.kaggle/kaggle.json
    
    - name: Configure GDrive Remote
      run: |
        echo ${{ secrets.SERVICE_ACCOUNT_TOKEN_BASE64 }} | base64 --decode > service-account-token.json
        dvc remote add --default gdrive gdrive://${{ secrets.DRIVE_URL }}
        dvc remote modify gdrive gdrive_use_service_account true
        dvc remote modify gdrive --local gdrive_service_account_json_file_path service-account-token.json

    - name: Install dependencies
      run: |        
        export PYTHONPATH=$PWD/src
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
        python setup.py sdist bdist_wheel
        pip install -e . 

    - name: Run Project Scripts
      run: |
        # python template.py
        dvc repro
        dvc exp run 
        dvc push
        
    # - name: tests
    #   run: pytest

    - name: Generate CML Report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "# Experiment Results" >> report.md
        echo "## Parameters Combination:" >> report.md
        echo "```yaml" >> report.md
        cat params.yaml >> report.md  # Assuming your parameters are in params.yaml
        echo "```"p >> report.md        

        # dvc metrics diff main >> report.md 
        echo "## Model Performence" >> report.md
        cat artifacts/classification_report.txt >> report.md
        echo "![](./artifacts/confusion_matrix.png)" >> report.md
        echo "![](./artifacts/auc_plot.png)" >> report.md
        echo "![](./artifacts/pr_curve.png)" >> report.md
        cml comment create report.md