name: CI Prediction Model

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - src/**
  pull_request:
    branches:
      - develop
    paths:
      - src/**

permissions: write-all
  # contents: read
  # id-token: write
jobs:
  experiment:
    environment: env
    runs-on: ubuntu-22.04 #ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"  
    
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: iterative/setup-cml@v1
    - uses: iterative/setup-dvc@v1

    - name: Handle Environment
      run: |
        export PYTHONPATH=$PWD/src
        echo "{\"username\": \"${{ vars.KAGGLE_USERNAME }}\", \"key\": \"${{ secrets.KAGGLE_KEY }}\"}" > kaggle.json
        chmod 600 kaggle.json
        mkdir -p ~/.kaggle
        cp kaggle.json ~/.kaggle/kaggle.json
        
    - name: Configure DVC Remote
      run: |
        dvc remote add -d gdrive dvc://?token=${{ secrets.DRIVE_URL }}
        dvc remote default gdrive
        whoami

    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
        python setup.py sdist bdist_wheel
        pip install -e . 

    - name: Run Project Scripts
      # env:
      #   GDRIVE_CERDENTIAL_DATA: ${{secrets.GDRIVE_TOKEN}}
      run: |
        python template.py
        # dvc pull data 
        dvc repro
        # dvc cache dir $PWD/.dvc/cache
        # sudo chmod -R a+rwx $PWD/.dvc/cache
        # dvc push
        
    # - name: tests
    #   run: pytest

    - name: Generate CML Report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # npm install -g @dvcorg/cml
        echo "## Reproduce Results" >> report.md
        echo "Use this parameters combination" >> report.md
        # dvc metrics diff main >> report.md
        cat artifacts/classification_report.txt >> report.md
        echo "![](./artifacts/confusion_matrix.png)" >> report.md
        echo "![](./artifacts/auc_plot.png)" >> report.md
        echo "![](./artifacts/pr_curve.png)" >> report.md
        cml comment create report.md 