name: Continous Integration for Prediction Model
on:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  experiment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox tox-gh-actions
        pip install -r requirements.txt

    # export "PYTHONPATH=\$PYTHONPATH:./src" >> $GITHUB_ENV

    # - name: Setup DVC
    #   uses: iterative/setup-cml@v1
    #   with:
    #     dvc_version: "3.0.0"

    # - name: Test with tox
    #   run: tox

    - name: Run Project Scripts
      run: |
        python template.py
        dvc repro
        # dvc push

    - name: Generate CML Report
      env:
        REPO_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "## Reproduce Results" >> report.md
        echo "Use this parameters compination" >> report.md
        dvc metrics diff main 
        cat "artifacts/classification_report.txt" >> report.md
        echo "![](./artifacts/confusion_matrix.png)" >> report.md
        echo "![](./artifacts/auc_plot.png)" >> report.md
        echo "![](./artifacts/pr_curve.png)" >> report.md
        cml comment create report.md
