name:
on: [push]
permessions: write-all

jobs:

  runs-on: ubuntu-latest
  steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-cml@v1
    - uses: actions/setup-node@v3
          with: 
            node-version: '16'
    - uses: actions/python@v4
          with: 
            python-version: '3.x'

    name: Prepare Environment
    - run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python template.py
        dvc repro

    - name: Generate CML Report
      env: 
          REPO TOKEN: ${{ secrets.GITHUB TOKEN}}
      run:
        echo "## Reproduce Results" >> report.md
        echo "Use this parameters compination" >> report.md
        cat "params.yaml" >> report.md
        cat "classification_report.txt" >> report.md
        echo "![](./artifacts/confusion_matrix.png)"

        