
name: CI/CD for Python Package and Pipeline

on:
  push:
    branches:

jobs:
  build_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload package to PyPI (optional)
        uses: pypa/gh-action-pypi-publish@v1  # Use this if you want to publish to PyPI
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}  # Replace with your PyPI token
          repository: forest-fire # Replace with the package name

  run_pipeline:
    needs: build_package  # This job depends on 'build_package'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .  # Install the package in editable mode

      - name: Configure DVC Remote (optional)
        run: |
          # Replace with your GDrive URL
          dvc remote add -d gdrive dvc://?token=<your-drive-url>
          dvc remote default gdrive

      - name: Run DVC pipeline
        run: dvc repro

      - name: Upload artifacts to GDrive (optional)
        run: dvc push  # Use this if you want to push artifacts to GDrive

      - name: Generate CML Report (optional)
        env:
          REPO_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "## Reproduce Results" >> report.md
          echo "Use this parameters combination" >> report.md
          dvc metrics diff main >> report.md
          cat artifacts/classification_report.txt >> report.md
          echo "![](./artifacts/confusion_matrix.png)" >> report.md
          echo "![](./artifacts/auc_plot.png)" >> report.md
          echo "![](./artifacts/pr_curve.png)" >> report.md
          cml comment create report.md